project:
  type: book
  output-dir: docs

book:
  title: "统计学与R语言"
  author: "陆海波"
  date: last-modified
  chapters:
    - index.qmd
    - syllbus.qmd
    - part: "课程内容"
      chapters:
        - week01.qmd
        - week02.qmd
        - week03.qmd
        - week04.qmd

format:
  html:
    theme: cosmo
    code-fold: false
    number-sections: false
    toc: true
    toc-depth: 3

execute:
  freeze: auto 