project:
  type: book
  output-dir: _book

book:
  title: "统计学与R语言"
  author: "陆海波"
  date: last-modified
  repo-url: https://github.com/h-lu/stat2025
  chapters:
    - index.qmd
    - syllbus.qmd
    - part: "项目一：统计分析基础与数据可视化"
      chapters:
        - week1.qmd
        - week2.qmd
        - week3.qmd
        - week4.qmd
    - part: "项目二：商业数据分析与统计推断"
      chapters:
        - week5.qmd
        - week6.qmd
        - week7.qmd
        - week8.qmd
        
format:
  html:
    theme: cosmo
    css:
      - styles/custom.css
      - styles/mermaid.css
    code-fold: false
    number-sections: false
    toc: true
    toc-depth: 3
    mainfont: "Noto Sans SC"

knitr:
  opts_chunk:
    dev: "ragg_png"
    dpi: 300
    fig.width: 8
    fig.height: 6
    fig.showtext: true
    
execute:
  freeze: auto
  echo: true
  warning: false
  message: false 